import { PrismaClient } from '@prisma/client';

export async function seedTests(prisma: PrismaClient) {
  console.log('🔄 Seeding tests...');

  await prisma.test.createMany({
    skipDuplicates: true,
    data: [
      // ── BLOOD ──────────────────────────────────────────────────────────
      {
        name: 'Complete Blood Count (CBC)',
        description: '24 parameters: RBC, WBC, Hb, Platelets, Differential.',
        price: 499, discountedPrice: 299,
        categoryId: 'blood',
        reportTime: '12 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.8, reviewCount: 1240, displayOrder: 1,
        isFeatured: true, isPopular: true,
        whyRequired: 'CBC is a fundamental test used to evaluate your overall health and detect a wide range of disorders, including anemia, infection and leukemia.',
      },
      {
        name: 'ESR (Westergren Method)',
        description: 'Inflammation marker — TB, infections, autoimmune.',
        price: 149, discountedPrice: 79,
        categoryId: 'blood',
        reportTime: '12 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.6, reviewCount: 850, displayOrder: 2,
        whyRequired: 'Erythrocyte sedimentation rate (ESR) measures how quickly red blood cells settle at the bottom of a test tube.',
      },
      {
        name: 'Urine Routine & Microscopy',
        description: '19 parameters: Physical, Chemical, Microscopic exam.',
        price: 199, discountedPrice: 99,
        categoryId: 'blood',
        reportTime: '12 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.9, reviewCount: 512, displayOrder: 3,
        whyRequired: 'Checks for signs of disease, such as diabetes or urinary tract infections.',
      },
      {
        name: 'Peripheral Smear Examination',
        description: 'Detects blood disorders and infections.',
        price: 349, discountedPrice: 199,
        categoryId: 'blood',
        reportTime: '24 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.7, reviewCount: 312, displayOrder: 4,
        whyRequired: 'Provides information about the number and shape of blood cells to diagnose infections and blood disorders.',
      },
      {
        name: 'Blood Group & Rh Typing',
        description: 'Determines blood type and Rh factor.',
        price: 299, discountedPrice: 149,
        categoryId: 'blood',
        reportTime: '12 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.8, reviewCount: 900, displayOrder: 5,
        whyRequired: 'Crucial test before a blood transfusion, surgery, or during pregnancy.',
      },

      // ── DIABETES ───────────────────────────────────────────────────────
      {
        name: 'Blood Sugar Fasting',
        description: 'Glucose after 8–12 hr fast.',
        price: 149, discountedPrice: 79,
        categoryId: 'diabetes',
        reportTime: '12 Hours', fastingRequired: true, homeCollection: true,
        rating: 4.5, reviewCount: 320, displayOrder: 1,
        isPopular: true,
        whyRequired: 'Used to measure your blood sugar level after fasting. High levels can indicate diabetes or insulin resistance.',
      },
      {
        name: 'HbA1c – 3-Month Average',
        description: 'Gold standard diabetes monitoring.',
        price: 549, discountedPrice: 299,
        categoryId: 'diabetes',
        reportTime: '24 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.9, reviewCount: 950, displayOrder: 2,
        isFeatured: true, isPopular: true,
        whyRequired: 'Tells you your average level of blood sugar over the past 2 to 3 months.',
      },
      {
        name: 'Blood Sugar PP',
        description: 'Checks sugar after meals.',
        price: 169, discountedPrice: 89,
        categoryId: 'diabetes',
        reportTime: '12 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.6, reviewCount: 412, displayOrder: 3,
        whyRequired: 'Measures blood glucose exactly 2 hours after you start eating a meal.',
      },
      {
        name: 'Insulin Fasting',
        description: 'Measures insulin resistance.',
        price: 1099, discountedPrice: 699,
        categoryId: 'diabetes',
        reportTime: '24 Hours', fastingRequired: true, homeCollection: true,
        rating: 4.8, reviewCount: 210, displayOrder: 4,
        whyRequired: 'Helps evaluate insulin resistance, key in the development of type 2 diabetes.',
      },

      // ── THYROID ────────────────────────────────────────────────────────
      {
        name: 'Thyroid Profile T3/T4/TSH',
        description: 'Complete thyroid hormone assessment.',
        price: 649, discountedPrice: 349,
        categoryId: 'thyroid',
        reportTime: '12 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.7, reviewCount: 430, displayOrder: 1,
        isPopular: true,
        whyRequired: 'Checks how well your thyroid gland is working and helps diagnose thyroid disorders.',
      },
      {
        name: 'Thyroid Free FT3/FT4/TSH',
        description: 'Free fraction — more accurate for patients on meds.',
        price: 799, discountedPrice: 449,
        categoryId: 'thyroid',
        reportTime: '24 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.8, reviewCount: 670, displayOrder: 2,
        whyRequired: 'Measures free fractions of T3 and T4, providing a more accurate assessment.',
      },
      {
        name: 'TSH Ultra Sensitive',
        description: 'Detects thyroid imbalance.',
        price: 449, discountedPrice: 249,
        categoryId: 'thyroid',
        reportTime: '12 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.6, reviewCount: 800, displayOrder: 3,
        whyRequired: 'Highly sensitive test for mild thyroid imbalances.',
      },
      {
        name: 'Anti TPO Antibody',
        description: 'Detects autoimmune thyroid disease.',
        price: 1399, discountedPrice: 799,
        categoryId: 'thyroid',
        reportTime: '24 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.8, reviewCount: 310, displayOrder: 4,
        whyRequired: 'Used to diagnose Hashimoto\'s disease and other autoimmune thyroid disorders.',
      },

      // ── CARDIAC ────────────────────────────────────────────────────────
      {
        name: 'Lipid Profile (7 param)',
        description: 'Cholesterol, HDL, LDL, VLDL, Triglycerides, CRI.',
        price: 599, discountedPrice: 349,
        categoryId: 'cardiac',
        reportTime: '24 Hours', fastingRequired: true, homeCollection: true,
        rating: 4.8, reviewCount: 890, displayOrder: 1,
        isFeatured: true,
        whyRequired: 'Used to find abnormalities in lipids which can increase the risk of heart disease.',
      },
      {
        name: 'Troponin I',
        description: 'Gold standard heart attack marker.',
        price: 1299, discountedPrice: 799,
        categoryId: 'cardiac',
        reportTime: '6 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.8, reviewCount: 890, displayOrder: 2,
        whyRequired: 'Measures cardiac-specific troponin in the blood to help detect heart injury.',
      },
      {
        name: 'CRP (Cardiac Risk)',
        description: 'Inflammation and heart risk marker.',
        price: 899, discountedPrice: 499,
        categoryId: 'cardiac',
        reportTime: '12 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.7, reviewCount: 430, displayOrder: 3,
        whyRequired: 'High-sensitivity CRP measures inflammation linked to higher risk of heart disease.',
      },

      // ── LIVER ──────────────────────────────────────────────────────────
      {
        name: 'Liver Function Test (LFT)',
        description: 'Measures liver enzymes and bilirubin.',
        price: 699, discountedPrice: 399,
        categoryId: 'liver',
        reportTime: '12 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.8, reviewCount: 1200, displayOrder: 1,
        isPopular: true,
        whyRequired: 'Evaluates the overall health of your liver and helps diagnose liver diseases like hepatitis.',
      },
      {
        name: 'Bilirubin Total/Direct',
        description: 'Checks jaundice and liver condition.',
        price: 299, discountedPrice: 149,
        categoryId: 'liver',
        reportTime: '12 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.6, reviewCount: 500, displayOrder: 2,
        whyRequired: 'High bilirubin levels can cause jaundice, a sign of liver or bile duct issues.',
      },
      {
        name: 'SGPT (ALT)',
        description: 'Liver enzyme test.',
        price: 299, discountedPrice: 149,
        categoryId: 'liver',
        reportTime: '12 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.7, reviewCount: 800, displayOrder: 3,
        whyRequired: 'ALT is an enzyme found mostly in the liver; high levels indicate liver damage.',
      },
      {
        name: 'Hepatitis B Surface Antigen',
        description: 'Detects Hepatitis B infection.',
        price: 899, discountedPrice: 499,
        categoryId: 'liver',
        reportTime: '24 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.9, reviewCount: 430, displayOrder: 4,
        whyRequired: 'Crucial screening test to determine active Hepatitis B infection.',
      },

      // ── VITAMINS ───────────────────────────────────────────────────────
      {
        name: 'Vitamin D Total (25-OH)',
        description: 'Bone health & immunity. Common deficiency.',
        price: 1299, discountedPrice: 799,
        categoryId: 'vitamins',
        reportTime: '24 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.8, reviewCount: 890, displayOrder: 1,
        isFeatured: true, isPopular: true,
        whyRequired: 'Determines Vitamin D deficiency, essential for bone health and immune function.',
      },
      {
        name: 'Vitamin B12 (Cobalamin)',
        description: 'Nerve function & RBCs. Essential for vegetarians.',
        price: 849, discountedPrice: 499,
        categoryId: 'vitamins',
        reportTime: '24 Hours', fastingRequired: true, homeCollection: true,
        rating: 4.8, reviewCount: 890, displayOrder: 2,
        isPopular: true,
        whyRequired: 'Checks for Vitamin B12 deficiency which can cause anemia, fatigue, and nerve damage.',
      },
      {
        name: 'Iron Profile',
        description: 'Checks iron deficiency and anemia.',
        price: 1199, discountedPrice: 699,
        categoryId: 'vitamins',
        reportTime: '12 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.7, reviewCount: 550, displayOrder: 3,
        whyRequired: 'Evaluates the amount of iron in your body and diagnoses iron-deficiency anemia.',
      },
      {
        name: 'Calcium Test',
        description: 'Bone health screening.',
        price: 349, discountedPrice: 199,
        categoryId: 'vitamins',
        reportTime: '12 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.6, reviewCount: 320, displayOrder: 4,
        whyRequired: 'Used to screen for conditions related to bones, heart, nerves, and kidneys.',
      },

      // ── FEVER ──────────────────────────────────────────────────────────
      {
        name: 'Dengue Duo NS1+IgG+IgM',
        description: '3-in-1 Dengue — NS1 antigen + IgG + IgM antibodies.',
        price: 1099, discountedPrice: 699,
        categoryId: 'fever',
        reportTime: '12 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.8, reviewCount: 890, displayOrder: 1,
        isTrending: true,
        whyRequired: 'Used to diagnose dengue fever early by detecting antigens and antibodies.',
      },
      {
        name: 'Typhoid Rapid Test',
        description: 'Quick antigen detection — results in 15 minutes.',
        price: 349, discountedPrice: 199,
        categoryId: 'fever',
        reportTime: '1 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.8, reviewCount: 890, displayOrder: 2,
        isTrending: true,
        whyRequired: 'Rapid detection of Salmonella Typhi antigens for quick typhoid diagnosis.',
      },
      {
        name: 'Malaria PF/PV Rapid',
        description: 'Differentiates P. Falciparum vs P. Vivax rapidly.',
        price: 449, discountedPrice: 249,
        categoryId: 'fever',
        reportTime: '1 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.8, reviewCount: 890, displayOrder: 3,
        isTrending: true,
        whyRequired: 'Rapid diagnosis of Malaria and differentiation of species for appropriate treatment.',
      },
      {
        name: 'CRP Quantitative',
        description: 'Detects infection and inflammation.',
        price: 649, discountedPrice: 349,
        categoryId: 'fever',
        reportTime: '12 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.7, reviewCount: 550, displayOrder: 4,
        whyRequired: 'Indicates presence of inflammation, useful for diagnosing bacterial infections.',
      },
      {
        name: 'COVID-19 RT PCR',
        description: 'Coronavirus detection test.',
        price: 1499, discountedPrice: 799,
        categoryId: 'fever',
        reportTime: '24 Hours', fastingRequired: false, homeCollection: true,
        rating: 4.9, reviewCount: 2000, displayOrder: 5,
        whyRequired: 'Gold standard test to accurately detect the SARS-CoV-2 virus.',
      },
    ],
  });

  console.log('✅ Tests seeded (29 tests across 7 categories)');
}